### ISSUE TITLE
TADS 3 upper windows aren't grid windows

### ISSUE THREAD

**Issue by curiousdannii** [curiousdannii/emglken#22]
TADS 3 upper windows aren't grid windows, but they are in Gargoyle. Which is very off, because they should be the same!

**Comment by curiousdannii** [comment]
@cspiegel Any ideas what could be causing this difference? I checked my CMake code, and it looks pretty much the same as yours: https://github.com/curiousdannii/emglken/blob/master/CMakeLists.txt#L77

The only thing we're not defining is GARGLK, but the only code I can see in TADS that's gated by it is this, which doesn't look relevant either:
https://github.com/garglk/garglk/blob/b6a89bebf7f7923c7253d59cc4fa216e240a19ad/terps/tads/osglkban.c#L535

Now my garglk submodule is a little bit old, but it didn't look like you'd done any relevant commits either.

**Comment by curiousdannii** [comment]
[In the forum RealNC explained](https://intfiction.org/t/how-are-the-tads-menus-generated/53555/7?u=dannii) that TADS doesn't make grid windows, but instead uses fixed width fonts. If it uses stylehints to do so, then that means I'd need to add full stylehint support to RemGlk to fix this...

**Comment by cspiegel** [comment]
It looks like TADS has the concept of a text-grid banner, with `osifc.h` doing this:

```
#define OS_BANNER_TYPE_TEXTGRID   2
```
And https://www.tads.org/t3doc/doc/sysman/banners.htm agrees with this, noting that text grids, in TADS, should generally not be used, with normal text buffer banner windows + HTML being preferred.  So that's probably why most games wouldn't be using a text grid.

In `osglkban.c`, the `os_banner_styles_apply` function is what ultimately makes the status bar have the "traditional" fixed look.  If the banner is meant to be a status window, proportional fonts are disabled.  So yes, it looks like RemGlk will need stylehint support, at least for the proportional, textcolor, and backcolor hints.

**Comment by curiousdannii** [comment]
I've added stylehint support, which is definitely an improvement, however now the status window lines are too long:
https://iplayif.com/?story=https://www.ifarchive.org/if-archive/games/tads/Fake_News.t3

I assume this is because the measurements for fixed width characters are wider than proportional characters. If only the banners could use true grid windows.

**Comment by curiousdannii** [comment]
So garglk appears to return glk_window_get_size results for text buffer windows based on the text grid font sizes. Simple, no problems there.

I think Windows-Glk and Spatterlight are returning sizes based on the font for each window (as the spec says it should do.)

@angstsmurf Do you know if Spatterlight is doing anything to stop this problem of the width of a line of fixed width text being too long for a buffer window?

**Comment by angstsmurf** [comment]
I don't remember the details, but I created a custom "Glk extension" function that returns the width that TADS requires for its banner calculations. 

I think both Spatterlight and Gargoyle has another custom function to help TADS calculate the banner height, by the way.

**Comment by curiousdannii** [comment]
Ah interesting. I was considering overriding the metrics returned by GlkOte, because how much use really is the proportional width of a window?

But a custom function could be useful. Or TADS could just make a temporary grid window and measure that? It wouldn't even need a Glk extension.

**Comment by angstsmurf** [comment]
I think that there was a problem with reporting the width in characters, because if the TADS banner is *not* using a fixed font style, the actual number of characters that fit can't really be calculated, but TADS expected the correct width anyway, before even printing the text. This led to ugly line breaks at the wrong position.

**Comment by curiousdannii** [comment]
Yep that's the problem I'm seeing now.
