### ISSUE TITLE
Enable (and document) WASM debugging

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/emglken#23]
Supposedly Chrome has facilities for WASM debugging with debug symbols.

https://developer.chrome.com/blog/wasm-debugging-2020/

It would be amazing if Parchment could do this automagically. (Presumably this will require emglken to provide debug / release builds…?)

**Comment by curiousdannii** [comment]
So I kind of got source maps for WASM working, but not in a way that's really reliable enough. If you uncomment out these lines then it will build source maps, however you'll also have to adjust the `--source-map-base` setting to refer to the path you will be publishing to (I couldn't work out any way to make it apply generally, like `.` for the same directory):

https://github.com/curiousdannii/emglken/blob/aa4db31d8822a1216e783c31617eb75c338a3233/src/common.cmake#L30-L33

If you use them it will report the correct function names, however you can't explore inside the file in dev tools, not even to open up the WASM instructions. And because it changes the debug settings it might be worse performance.

With all these caveats I don't think I can justify turning it on by default, even if I could work out the path problem. But it is there to manually enable for those rare situations in which it might help uncover a bug.

**Comment by curiousdannii** [comment]
I found out there's another setting which just embeds function names for use in stack traces etc. Seeing as the source maps weren't useable as actual source maps, I've swapped out the source maps settings for it and enabled it by default!

**Comment by curiousdannii** [comment]
Now that I'm using RemGlk-rs, this is adding between 49kb (Hugo) and 188kb (TADS). I think I'm going to still keep the function names in, as it's just too useful when there's an error. hugo.wasm has grown to 1MB anyway, so an extra 44kb is pretty insignificant.
